### ISSUE TITLE
Travis-CI not working with hugo v0.54.0 anymore

### ISSUE THREAD

**Issue by mrustl** [yihui/travis-blogdown#1]
See issue: https://travis-ci.community/t/r-with-hugo-v0-54-0-glibcxx-3-4-20-and-glibcxx-3-4-21-not-found/2365

Do you have the same problem?

**Comment by yihui** [comment]
You may try `dist: xenial`: https://discourse.gohugo.io/t/13029/8

**Comment by yihui** [comment]
BTW, you should mention in your Travis Community post that [you also cross-posted](https://yihui.name/en/2017/10/cross-posting/) the issue here (to avoid duplicated effort in helping you).

**Comment by mrustl** [comment]
Thanks for helping out. Followed your recommendation on cross-posting

**Comment by yihui** [comment]
Perfect. Thanks!
